# Generated by Django 4.1.4 on 2022-12-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='prefix',
            field=models.SlugField(null=True, unique=True, verbose_name='Prefix'),
        ),
    ]
