# Generated by Django 4.1.4 on 2022-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_team_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='prefix',
            field=models.SlugField(blank=True, default=1, unique=True, verbose_name='Prefix'),
            preserve_default=False,
        ),
    ]
