# Generated by Django 4.1.4 on 2022-12-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='accept',
        ),
    ]
