# Generated by Django 4.1.4 on 2022-12-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_proposal_accept'),
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.team', verbose_name='Team'),
        ),
    ]
